name: Deploy to Somee via FTP

on:
  push:
    branches: ["main"]   # Tự deploy khi push vào main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: FTP Deploy to Somee
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.SOME_FTP_SERVER }}
        username: ${{ secrets.SOME_FTP_USERNAME }}
        password: ${{ secrets.SOME_FTP_PASSWORD }}
        protocol: ftp
        server-dir: /   # thư mục root hosting somee;
