name: Deploy to Somee via FTP

on:
  push:
    branches: ["main"]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Somee FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: "155.254.246.47"
          username: ${{ secrets.SOME_FTP_USERNAME }}
          password: ${{ secrets.SOME_FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: "/www.nguyenthechuong.somee.com/"
          local-dir: "."
          log-level: verbose
